stages:
  - build
  - deploy

build:
  script:
    - make czechia

#deploy:
#  script:
#    - mkdir .public
#    - cp -r build/* .public
#    - mv .public public
#  artifacts:
#    paths:
#      - public
#  only:
#    - master